-- MySQL Script generated by MySQL Workbench
-- Mon Mar  8 16:47:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ukk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ukk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ukk` DEFAULT CHARACTER SET utf8 ;
USE `ukk` ;

-- -----------------------------------------------------
-- Table `ukk`.`masyarakat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ukk`.`masyarakat` (
  `nik` CHAR(16) NOT NULL,
  `nama` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `telp` VARCHAR(45) NULL,
  PRIMARY KEY (`nik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ukk`.`pengaduan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ukk`.`pengaduan` (
  `id_pengaduan` INT NOT NULL AUTO_INCREMENT,
  `tgl_pengaduan` DATETIME NULL,
  `isi_pengaduan` TEXT NULL,
  `foto` VARCHAR(255) NULL,
  `status` ENUM('0', 'proses', 'selesai') NULL,
  `nik` CHAR(16) NULL,
  PRIMARY KEY (`id_pengaduan`),
  CONSTRAINT `nik`
    FOREIGN KEY (`nik`)
    REFERENCES `ukk`.`masyarakat` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ukk`.`petugas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ukk`.`petugas` (
  `id_petugas` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `telp` VARCHAR(45) NULL,
  `level` ENUM('admin', 'petugas') NULL,
  PRIMARY KEY (`id_petugas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ukk`.`tanggapan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ukk`.`tanggapan` (
  `id_tanggapan` INT NOT NULL AUTO_INCREMENT,
  `tanggal` DATETIME NULL,
  `tanggapan` TEXT NULL,
  `id_pengaduan` INT NULL,
  `id_petugas` INT NULL,
  PRIMARY KEY (`id_tanggapan`),
  CONSTRAINT `id_pengaduan`
    FOREIGN KEY (`id_pengaduan`)
    REFERENCES `ukk`.`pengaduan` (`id_pengaduan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_petugas`
    FOREIGN KEY (`id_petugas`)
    REFERENCES `ukk`.`petugas` (`id_petugas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
