-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 13:18:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tanggapan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tanggapan` (
  `id_tanggapan` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pengaduan` INT(11) NULL,
  `tgl_tanggapan` DATE NULL,
  `tanggapan` TEXT NULL,
  `id_petugas` INT(11) NULL,
  PRIMARY KEY (`id_tanggapan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pengaduan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pengaduan` (
  `id_pengaduan` INT(11) NOT NULL AUTO_INCREMENT,
  `tgl_pengaduan` DATE NULL,
  `nik` CHAR(16) NULL,
  `isi_laporan` TEXT NULL,
  `foto` VARCHAR(255) NULL,
  `status` ENUM('0', 'proses', 'selesai') NULL,
  PRIMARY KEY (`id_pengaduan`),
  CONSTRAINT `id_pengaduan`
    FOREIGN KEY (`id_pengaduan`)
    REFERENCES `mydb`.`tanggapan` (`id_pengaduan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`masyarakat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`masyarakat` (
  `nik` CHAR NOT NULL,
  `nama` VARCHAR(35) NULL,
  `username` VARCHAR(25) NULL,
  `password` VARCHAR(32) NULL,
  `telp` VARCHAR(13) NULL,
  PRIMARY KEY (`nik`),
  CONSTRAINT `nik`
    FOREIGN KEY (`nik`)
    REFERENCES `mydb`.`pengaduan` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`petugas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`petugas` (
  `id_petugas` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_petugas` VARCHAR(35) NULL,
  `username` VARCHAR(25) NULL,
  `password` VARCHAR(32) NULL,
  `telp` VARCHAR(13) NULL,
  `level` ENUM('admin', 'petugas') NULL,
  PRIMARY KEY (`id_petugas`),
  CONSTRAINT `id_petugas`
    FOREIGN KEY (`id_petugas`)
    REFERENCES `mydb`.`tanggapan` (`id_petugas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
